config/routes.rb
Rails.application.routes.draw do

  get "users/all", to: "users#list_users"

  resources :home

  devise_for :users, controllers: { registrations: "registrations" }

  resources :notes, only:[:create, :new, :destroy, :edit, :update, :show] do
    resources :comments
  end

  resources :users do
    resources :notes
  end

  get "users/:user_id/preferences", to: "users#preferences"

  get "users/:user_id/preferences/update", to: "users#set_preferences"

  get "/new", to: "home#new"

  get "/questions", to: "home#questions"

  get "/search", to: "home#search"

  root "home#questions"

end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :note
	belongs_to :user
end

app/models/language.rb
class Language < ActiveRecord::Base
	has_many :natives , :class_name => "User"
	has_many :users, :through => :learning
	has_many :notes
end

app/models/learning.rb
class Learning < ActiveRecord::Base
	belongs_to :user
	belongs_to :language
end

app/models/note.rb
class Note < ActiveRecord::Base
	belongs_to :user
	belongs_to :language

	has_many :comments
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :notes, dependent: :destroy

  belongs_to :native , :foreign_key => "language_id",  :class_name => "Language"
  has_many :learning
  has_many :languages, :through => :learning
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  include ActionView::Helpers::TagHelper
  include ActionView::Context    

  
  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

    def configure_permitted_parameters
        devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:email, :password, :username, :language_id, :languages_learning) }
        devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:email, :password, :current_password, :language_id, :languages_learning) }
    end

  helper_method :get_languages, :get_language_name, :shorten_note, :embed_youtube, :is_youtube?

    def get_languages
      languages = LanguageList::COMMON_LANGUAGES
      languages.sort!
      return languages
    end

    def get_language_name(id)
      language = Language.find(id)
      return language.name
    end

    def shorten_note(text)
      new_text = text[0,300]
      if new_text.length < text.length
        new_text = new_text + "…"
      end
      return new_text
    end

    def convert_time(time)
      if time.include? "m"
        time_seconds = (time.scan(/\d+/).first.to_i * 60) + (time.scan(/\d+/).first.to_i)
        return time_seconds.to_s
      else
        return time.scan(/\d+/).first
      end
    end

    def embed_youtube(youtube_url)
        regex = /^(?:https?:\/\/)?(?:www\.)?youtu(?:\.be|be\.com)\/(?:watch\?v=)?([\w-]{10,})/
        youtube_id = youtube_url.match(regex)[1]

        timestamp = youtube_url.split("?t=").last
        
        if timestamp.length
          youtube_id += "?start=" + convert_time(timestamp)
        end

        content_tag(:iframe, nil, src: "//www.youtube.com/embed/#{youtube_id}")
    end

    def is_youtube?(url)
      regex = /^(?:https?:\/\/)?(?:www\.)?youtu(?:\.be|be\.com)\/(?:watch\?v=)?([\w-]{10,})/
      if url.match(regex) != nil
        return true
      else
        return false
      end
    end


end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    new_comment = current_user.comments.create(:text => params[:comment][:text], :note_id => params[:note_id])

    new_comment.save

    redirect_to "/users/#{current_user.id}/notes/#{params[:note_id]}"
  end

  def destroy
    comment = Comment.find(params[:id])
    user = Note.find(params[:note_id]).user
    if user_signed_in? && user['id'] == current_user.id
      Comment.destroy(params[:id])
    end

    note = comment.note
    redirect_to note_path(note)  
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def questions
  	if user_signed_in?
  		@languages = current_user.languages
  	else
  		@languages = Language.all
  	end
    if user_signed_in?
      @notes = Note.where(question: true, language_id: current_user['language_id']).order(:created_at).reverse_order
    else
      @path = "/questions"  
      @q = Note.ransack(params[:q])
      @notes = @q.result.where(question: true).order(:created_at).reverse_order
    end
  end

  def new
  	if user_signed_in?
  		@languages = current_user.languages
  	else
  		@languages = Language.all
  	end
  	@path = "/new" 	
  	@q = Note.ransack(params[:q])
  	@notes = @q.result.where(private: nil).order(:created_at).reverse_order
  end

  def search
  	@path = "/search"
  	@q = User.ransack(params[:q])
  	@notes = @q.result.where(private: nil).order(:created_at).reverse_order
  end

end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  def index
  end

  def show
    @note = Note.find(params[:id])
    @user = User.find(@note['user_id'])

    if @note['private'] != true || (user_signed_in? && @user['id'] == current_user.id)
      @language = Language.find(@note['language_id'])
      if is_youtube?(@note['source'])
        @youtube = true
      else
        @youtube = false
      end
      @comment = Comment.new
      @comments = @note.comments.order(:created_at).reverse_order
    else
      redirect_to "/"
    end

  end

  def new
    @note = Note.new
    @user = current_user
    @method = "post"
    @route = notes_path
  end

  def create
    new_note = current_user.notes.create(note_params)
    new_note.save

    redirect_to "/users/#{current_user.id}"
  end

  def edit
    @note = Note.find(params[:id])
    @user = @note.user

    if user_signed_in? && @user['id'] == current_user.id
      @method = "put"
      @route = note_path
    else
      redirect_to "/"
    end    
  end

  def update
    note = Note.find(params[:id])
    
    if params[:private] == nil
      note.private = nil
    end
    
    if params[:question] == nil
      note.question = nil
    end
    
    note.update(note_params)

    redirect_to note_path
  end

  def destroy
    user = Note.find(params[:id]).user
    if user_signed_in? && user['id'] == current_user.id
      Note.destroy(params[:id])
      redirect_to user_path(current_user)
    else
      redirect_to "/"
    end
  end

  def note_params
    params.require(:note).permit( :title, :language_id, :body, :source, :question, :private )
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
	protected

	  def after_sign_up_path_for(resource)
	  	current_user_id = current_user.id
	    "/users/#{current_user_id}/preferences" # Or :prefix_to_your_route
	  end

	  def after_inactive_sign_up_path_for(resource)
	    current_user_id = current_user.id
	   	"/users/#{current_user_id}/preferences"
	  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
  	@user = User.find(params[:id])
    if user_signed_in?
      @languages = @user.languages
    else
      @languages = Language.all
    end
    @path = user_path
    @q = Note.ransack(params[:q])
    @notes = @q.result.where(user_id: params[:id]).order(:created_at).reverse_order
  end


  def preferences
  	@user = current_user
  end


  def list_users
  	@q = User.ransack(params[:q])
    @users = @q.result
  end


  def set_preferences

  	language_ids = params[:user][:language_ids]

  	language_ids.each do |id|
  		new_learning = Learning.new(user_id: params[:user_id], language_id: id)
  		new_learning.save
  	end

  	redirect_to "/"
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/application/_homenotes.html.erb
<ul class="notes-container">

<% @notes.each do |note| %>

	<li class="note-home">

		<%= link_to "#{note['title']}", note_path(note), class: "note-title" %>

		<%= link_to "#{note.user.username}", user_path(note.user), class: "note-username" %>

		<p class="note-language"><%= get_language_name(note['language_id']) %></p>

		<p class="note-body"><%= shorten_note(note['body']) %></p>

		<i class="fa fa-comments"></i><%= link_to "#{note.comments.length} Comments", note_path(note), class: "note-comments-label" %>

	</li>

<% end %>

</ul>

app/views/application/_languagefilter.html.erb
<%= search_form_for @q, url: @path, class: "language-filter-form" do |f| %>

	<%= f.label :language_id_eq, "Filter by language" %>
	<%= f.collection_select :language_id_eq, @languages, :id, :name %>

  <button class="filter-button">Filter</button>

<% end %>

<a href="<%= @path %>" class="cancel-filter"><button>Cancel filter</button></a>

app/views/application/_nav.erb
<div class="sticky">
  <nav class="top-bar" data-topbar role="navigation">
    <ul class="title-area">
      <li class="name">
        <h1><a href="/">LangExchange</a></h1>
      </li>
       <!-- Remove the class "menu-icon" to get rid of menu icon. Take out "Menu" to just have icon alone -->
      <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
    </ul>

    <section class="top-bar-section">
      <!-- Right Nav Section -->
      <ul class="right">
        <% if user_signed_in? %>
          <li class="has-dropdown">
            <a id="nav-username" href="#"><%= current_user.username %></a>
            <ul class="dropdown">
              <li><a href="/users/<%= current_user.id %>">Profile</a></li>
              <li><%= link_to('Logout', destroy_user_session_path, :method => :delete) %></li>

            </ul>
          </li>
        <% else %>
          <li>
            <%= link_to('Sign up', new_user_registration_path)  %>  
          </li>

          <li>
            <%= link_to('Login', new_user_session_path)  %>  
          </li>
        <% end %>
      </ul>

      <!-- Left Nav Section -->
      <ul class="left">
        <li><a href="/">Home</a></li>
        <li><a href="/users/all">Users</a></li>
        <li><a href="/questions">Questions</a></li>
        <li><a href="/new">Newly posted</a></li>
        <% if user_signed_in? %>
          <li><%= link_to "Add new note", new_note_path %></li>
        <% end %>
      </ul>
    </section>
  </nav>
</div>

app/views/application/_noteform.html.erb
<%= form_for(@note, url: @route, method: @method) do |f| %>

	<div class="field">
	  <%= f.label :language_id %>
	  <%= f.collection_select(:language_id, @user.languages, :id, :name) %>
	</div>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title, :required => true, autocomplete: "off" %>
  </div>

  <div class="field">
    <%= f.label :body %>
    <%= f.text_area :body, :required => true, autocomplete: "off" %>
  </div>

  <div class="field">
    <%= f.label :source %>
    <%= f.text_field :source, :placeholder => "Enter a URL (optional)", autocomplete: "off" %>
  </div>

  <div class="field">
    <%= f.check_box(:question, {:id => "question-checkbox"}, true, false) %>
    <%= f.label(:question, "Post as question", id: "question-label") %>
  </div>

  <div class="field">
    <%= f.check_box(:private, {:id => "private-checkbox"}, true, false) %>
    <%= f.label(:private, "Private note", id: "private-label") %>
  </div>
  

  <div class="actions">
    <button>Save</button>
  </div>

<% end %>

app/views/application/_usersearch.html.erb
<%= search_form_for @q, url: "/users/all", class: "user-search-form" do |f| %>

	<%= f.label :username_cont, "Search users" %>
	<%= f.text_field :username_cont, placeholder: "Enter username", autocomplete: "off" %>

  <button class="search-button">Search</button>

<% end %>

app/views/comments/delete.html.erb
<h1>Comments#delete</h1>
<p>Find me in app/views/comments/delete.html.erb</p>

app/views/comments/edit.html.erb
<h1>Comments#edit</h1>
<p>Find me in app/views/comments/edit.html.erb</p>

app/views/comments/new.html.erb
<h1>Comments#new</h1>
<p>Find me in app/views/comments/new.html.erb</p>

app/views/comments/update.html.erb
<h1>Comments#update</h1>
<p>Find me in app/views/comments/update.html.erb</p>

app/views/home/new.html.erb
<h1>Recent notes</h1>

<%= render "languagefilter" %>

<%= render "homenotes" %>

app/views/home/questions.html.erb
<h1>Newest questions</h1>

<% if user_signed_in? %>
	<h5>Respond to questions about your native language</h5>
<% else %>
	<%= render "languagefilter" %>
<% end %>

<%= render "homenotes" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "LangExchange" %></title>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>

    <%= render "nav" %>

  	<% if notice %>
  	  <p class="alert alert-success"><%= notice %></p>
  	<% end %>
  	<% if alert %>
  	  <p class="alert alert-danger"><%= alert %></p>
  	<% end %>

    <main>
      <%= yield %>
    </main>

  </body>
</html>

app/views/notes/create.html.erb
<h1>Notes#create</h1>
<p>Find me in app/views/notes/create.html.erb</p>

app/views/notes/destroy.html.erb
<h1>Notes#destroy</h1>
<p>Find me in app/views/notes/destroy.html.erb</p>

app/views/notes/edit.html.erb
<h1>Edit note</h1>

<%= render "application/noteform" %>

<%= link_to 'Cancel', user_note_path(@user, @note) %>

app/views/notes/index.html.erb
<h1>Notes#index</h1>
<p>Find me in app/views/notes/index.html.erb</p>

app/views/notes/new.html.erb
<h1>New note</h1>

<%= render "application/noteform" %>

<%= link_to "Cancel", user_path(@user), class: "new-note-cancel" %>

app/views/notes/show.html.erb
<h1><%= @note['title'] %></h1>

<h4 class="note-opened-created-by" >Created by: <%= link_to "#{@note.user.username}", user_path(@user) %></h3>

<% if @note['private'] %>
	<i class="fa fa-lock" title="This note is not visible to other users"></i>
	<p class="note-opened-private-label">Private</p>
	<br>
<% end %>

<% if @note['question'] %>
	<img class="megaphone" src="/img/megaphone.svg" title="This note is a question">
	<p class="note-opened-question-label">Posted as question</p>
	<br>
<% end %>

<h6>Posted <%= @note['created_at'] %></h6>

<p class="note-opened-language"><%= @language['name'] %></p>



<div class = "note-opened-links-icons">
	<% if user_signed_in? %>
		<%= link_to "Edit", edit_note_path(@note), class: "note-edit" %>
		<%= link_to 'Delete', user_note_path(@user, @note), :method => :delete, class: "note-delete" %>	
	<% end %>
</div>

<div class="note-opened-body">
<p><%= @note['body'] %></p>
</div>

<% if @note['source'].length > 0 %>

	<p class="source-label">Source:</p>

	<% if @youtube %>
		<div class="embed-container">
			<%= embed_youtube(@note['source']) %>
		</div>
	<% else %>
		<div class="note-opened-source">
			<p><%= auto_link(@note['source']) %></p>
		</div>
	<% end %>

<% end %>


<br>

<div class="comments-section-container">

<h4>Add new comment</h4>

<%= form_for(@comment, url: note_comments_path(@note), method: "post") do |f| %>

  <div class="field">
    <%= f.text_area :text %>
  </div>

  <div class="actions">
    <%= f.submit "Save" %>
  </div>

<% end %>


<br>

<h4>Comments</h4>

<ul class="comments-container">

	<% @comments.each do |comment| %>

		<li class="comment">

			<%= link_to comment.user.username, user_path(comment.user), class: "comment-username" %>
			<p class="comment-language">Native language: <%= get_language_name(comment.user.native) %></p>
			<p class="comment-time"><%= comment['created_at'] %></p>
			
			<p class="comment-text"><%= comment['text'] %></p>

			<% if user_signed_in? %>
				<%= link_to 'Delete', note_comment_path(@note,comment), :method => :delete, class: "comment-delete" %>
			<% end %>

		</li>


	<% end %>

	<% if @comments.length == 0 %>
		<p id="no-comments-message">Be the first to comment</p>
	<% end %>

</ul>

</div>

app/views/notes/update.html.erb
<h1>Notes#update</h1>
<p>Find me in app/views/notes/update.html.erb</p>

app/views/users/list_users.html.erb
<h1>Users</h1>

<%= render "usersearch" %>

<% @users.each_slice(3) do |slice| %>

	<div class="row">
		<% slice.each do |user| %>
			<div class="large-3 columns end user-tile">
				<a href="/users/<%= user['id'] %>"><%= user['username'] %></a>
				
				<p class="user-page-label">Native language: <%= get_language_name(user['language_id']) %></p>

			</div>
		<% end %>
	</div>
<% end %>

app/views/users/preferences.html.erb
<%= form_for(@user, url: "/users/#{@user['id']}/preferences/update", method: 'get') do |f| %>

  <div class="field">
    <%= f.label "Languages you're learning" %><br />
      <%= f.collection_check_boxes :language_ids, Language.all, :id, :name do |b| %>
        <div class="collection-check-box">
          <%= b.check_box %>
          <%= b.label %>
        </div>
      <% end %>

  </div>

	<div class="actions">
	  <%= f.submit "Save" %>
	</div>

<% end %>

app/views/users/show.html.erb
<h1><%= @user['username'] %>'s notes</h1>

<%= render "languagefilter" %>

<ul class="notes-container">

<% @notes.each do |note| %>

		<% if note['private']==nil || (user_signed_in? && current_user.id == note['user_id']) %>

			<li class="note">
				<%= link_to "#{note['title']}", note_path(note), class: "note-title" %>

				<%= link_to "#{note.user.username}", user_path(note.user), class: "note-username" %>

				<p class="note-language"><%= get_language_name(note['language_id']) %></p>

				<p class="note-body"><%= shorten_note(note['body']) %></p>

				<i class="fa fa-comments"></i><%= link_to "#{note.comments.length} Comments", note_path(note), class: "note-comments-label" %>
				
				<% if current_user %>
					<div class="edit-delete-links">
						<%= link_to "Edit", edit_note_path(note), class: "note-edit" %>
						<%= link_to 'Delete', note_path(note), :method => :delete, class: "note-delete" %>
					</div>
				<% end %>
			</li>

		<% end %>


<% end %>


</ul>